fn render_request_methods() -> Result<String> {
    let contracts = request_contracts();
    let mut methods = BTreeSet::new();
    let mut imports = BTreeSet::new();

    for contract in &contracts {
        if !methods.insert(contract.method) {
            bail!("duplicate Gateway request method: {}", contract.method);
        }
        imports.insert(contract.params_ts.as_str());
        if contract.result_ts != "GatewayJsonResult" {
            imports.insert(contract.result_ts.as_str());
        }
    }

    let mut ts = String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
    ts.push_str("import type {\n");
    for name in imports {
        ts.push_str("  ");
        ts.push_str(name);
        ts.push_str(",\n");
    }
    ts.push_str("} from './types';\n\n");
    ts.push_str("export type GatewayJsonResult = Record<string, unknown>;\n\n");
    ts.push_str("export interface GatewayRequestParams {\n");
    for contract in &contracts {
        ts.push_str("  \"");
        ts.push_str(contract.method);
        ts.push_str("\": ");
        ts.push_str(&contract.params_ts);
        ts.push_str(";\n");
    }
    ts.push_str("}\n\n");
    ts.push_str("export interface GatewayRequestResults {\n");
    for contract in &contracts {
        ts.push_str("  \"");
        ts.push_str(contract.method);
        ts.push_str("\": ");
        ts.push_str(&contract.result_ts);
        ts.push_str(";\n");
    }
    ts.push_str("}\n\n");
    ts.push_str("export type GatewayMethod = keyof GatewayRequestParams;\n");
    Ok(ts)
}
