import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv from "ajv";
import {
  gatewaySchemaRefs,
  gatewaySchemas,
  type GatewaySchemaName
} from "../src/generated/schemas/index.ts";

const check = process.argv.includes("--check");
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(packageRoot, "src/generated/validators.ts");
const names = Object.keys(gatewaySchemas) as GatewaySchemaName[];
const supportedKeywords = new Set([
  "$id",
  "$ref",
  "$schema",
  "additionalProperties",
  "allOf",
  "anyOf",
  "default",
  "definitions",
  "description",
  "enum",
  "format",
  "items",
  "maximum",
  "minimum",
  "oneOf",
  "properties",
  "required",
  "title",
  "type"
]);
const ajv = new Ajv({
  allErrors: false,
  strict: true,
  validateFormats: false
});

for (const format of [
  "double",
  "int32",
  "int64",
  "uint",
  "uint8",
  "uint16",
  "uint32",
  "uint64"
]) {
  ajv.addFormat(format, true);
}
for (const [index, schemaRef] of gatewaySchemaRefs.entries()) {
  assertInterpreterSchema(schemaRef, `gatewaySchemaRefs[${index}]`);
  ajv.addSchema(schemaRef);
}
for (const name of names) {
  assertInterpreterSchema(gatewaySchemas[name], name);
  ajv.addSchema(gatewaySchemas[name], name);
}
for (const name of names) {
  ajv.getSchema(name);
}

const compiledNames = names
  .map((name) => `  ${JSON.stringify(name)},`)
  .join("\n");
const output = [
  "// @generated by psychevo-xtask gateway-protocol generate",
  "",
  "export const strictlyCompiledGatewaySchemaNames = [",
  compiledNames,
  "] as const;",
  ""
].join("\n");

if (check) {
  let existing: string;
  try {
    existing = await readFile(outputPath, "utf8");
  } catch {
    throw new Error(`generated strict-compilation manifest is missing: ${outputPath}`);
  }
  if (existing !== output) {
    throw new Error(
      "generated strict-compilation manifest is stale; run "
      + "`cargo xtask gateway-protocol generate`"
    );
  }
} else {
  await writeFile(outputPath, output);
}

function assertInterpreterSchema(schema: unknown, location: string): void {
  if (typeof schema === "boolean") {
    return;
  }
  if (!schema || typeof schema !== "object" || Array.isArray(schema)) {
    throw new Error(`generated schema ${location} is not an object or boolean`);
  }
  const record = schema as Record<string, unknown>;
  for (const keyword of Object.keys(record)) {
    if (!supportedKeywords.has(keyword)) {
      throw new Error(
        `generated schema ${location} uses unsupported runtime keyword ${keyword}`
      );
    }
  }
  for (const keyword of ["properties", "definitions"]) {
    const children = record[keyword];
    if (children && typeof children === "object" && !Array.isArray(children)) {
      for (const [name, child] of Object.entries(children)) {
        assertInterpreterSchema(child, `${location}.${keyword}.${name}`);
      }
    }
  }
  for (const keyword of ["allOf", "anyOf", "oneOf"]) {
    const branches = record[keyword];
    if (Array.isArray(branches)) {
      branches.forEach((branch, index) => (
        assertInterpreterSchema(branch, `${location}.${keyword}[${index}]`)
      ));
    }
  }
  const items = record.items;
  if (Array.isArray(items)) {
    items.forEach((item, index) => (
      assertInterpreterSchema(item, `${location}.items[${index}]`)
    ));
  } else if (items != null) {
    assertInterpreterSchema(items, `${location}.items`);
  }
  if (
    record.additionalProperties != null
    && typeof record.additionalProperties !== "boolean"
  ) {
    assertInterpreterSchema(
      record.additionalProperties,
      `${location}.additionalProperties`
    );
  }
}
