#[derive(Debug, Clone, Copy)]
struct ExportedType {
    name: &'static str,
    ts_decl: fn() -> Result<String>,
    schema: fn() -> Result<Value>,
}

#[derive(Debug, Clone)]
struct SchemaGroupEntry {
    name: &'static str,
    json: String,
}

#[derive(Debug, Clone)]
struct SchemaRefEntry {
    export_name: String,
    import_path: String,
    json: String,
    schema_path: String,
}

pub fn generate_typescript_and_schema(repo_root: &Path, check: bool) -> Result<()> {
    let package_root = repo_root.join("packages/protocol");
    let generated_dir = package_root.join("src/generated");
    let generated_schema_dir = generated_dir.join("schemas");
    let schema_dir = package_root.join("schema");
    let mut ts = String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
    for exported in exported_types() {
        ts.push_str(&(exported.ts_decl)()?);
        ts.push_str("\n\n");
    }
    write_checked(&generated_dir.join("types.ts"), &ts, check)?;

    let legacy_schema_file = generated_dir.join("schemas.ts");
    if check {
        if legacy_schema_file.exists() {
            bail!(
                "obsolete generated file is present: {}",
                legacy_schema_file.display()
            );
        }
    } else {
        let _ = fs::remove_file(&legacy_schema_file);
        if generated_schema_dir.exists() {
            fs::remove_dir_all(&generated_schema_dir)?;
        }
        for composite in ["ClientRequest", "ServerNotification"] {
            let _ = fs::remove_dir_all(schema_dir.join(composite));
        }
    }

    let mut schema_groups: BTreeMap<&'static str, Vec<SchemaGroupEntry>> = BTreeMap::new();
    let mut schema_ref_groups: BTreeMap<&'static str, Vec<SchemaRefEntry>> = BTreeMap::new();
    for exported in exported_types() {
        let schema = (exported.schema)()?;
        let rendered = render_schema_export(exported.name, &schema)?;
        write_checked(
            &schema_dir.join(format!("{}.json", exported.name)),
            &(rendered.root_json.clone() + "\n"),
            check,
        )?;
        for ref_entry in &rendered.refs {
            write_checked(
                &schema_dir.join(&ref_entry.schema_path),
                &(ref_entry.json.clone() + "\n"),
                check,
            )?;
        }
        let module = schema_group_module(exported.name);
        schema_groups
            .entry(module)
            .or_default()
            .push(SchemaGroupEntry {
                name: exported.name,
                json: rendered.root_json,
            });
        schema_ref_groups
            .entry(module)
            .or_default()
            .extend(rendered.refs);
    }

    for (module, schemas) in &schema_groups {
        let mut group_ts =
            String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
        if let Some(refs) = schema_ref_groups.get(module) {
            for ref_entry in refs {
                group_ts.push_str("import { ");
                group_ts.push_str(&ref_entry.export_name);
                group_ts.push_str(" } from './");
                group_ts.push_str(&ref_entry.import_path);
                group_ts.push_str("';\n");
            }
            if !refs.is_empty() {
                group_ts.push('\n');
            }
        }
        group_ts.push_str("export const ");
        group_ts.push_str(schema_group_const(module));
        group_ts.push_str(" = {\n");
        for SchemaGroupEntry { name, json } in schemas {
            group_ts.push_str("  ");
            group_ts.push_str(name);
            group_ts.push_str(": ");
            group_ts.push_str(json);
            group_ts.push_str(",\n");
        }
        group_ts.push_str("} as const;\n");
        if let Some(refs) = schema_ref_groups.get(module)
            && !refs.is_empty()
        {
            group_ts.push_str("\nexport const ");
            group_ts.push_str(schema_group_refs_const(module));
            group_ts.push_str(" = [\n");
            for ref_entry in refs {
                group_ts.push_str("  ");
                group_ts.push_str(&ref_entry.export_name);
                group_ts.push_str(",\n");
            }
            group_ts.push_str("] as const;\n");
            for ref_entry in refs {
                let mut part_ts =
                    String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
                part_ts.push_str("export const ");
                part_ts.push_str(&ref_entry.export_name);
                part_ts.push_str(" = ");
                part_ts.push_str(&ref_entry.json);
                part_ts.push_str(" as const;\n");
                write_checked(
                    &generated_schema_dir.join(format!("{}.ts", ref_entry.import_path)),
                    &part_ts,
                    check,
                )?;
            }
        }
        write_checked(
            &generated_schema_dir.join(format!("{module}.ts")),
            &group_ts,
            check,
        )?;
    }

    let mut schemas_index =
        String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
    for module in schema_groups.keys() {
        schemas_index.push_str("import { ");
        schemas_index.push_str(schema_group_const(module));
        if schema_ref_groups
            .get(module)
            .is_some_and(|refs| !refs.is_empty())
        {
            schemas_index.push_str(", ");
            schemas_index.push_str(schema_group_refs_const(module));
        }
        schemas_index.push_str(" } from './");
        schemas_index.push_str(module);
        schemas_index.push_str("';\n");
    }
    schemas_index.push_str("\nexport const gatewaySchemas = {\n");
    for exported in exported_types() {
        let module = schema_group_module(exported.name);
        schemas_index.push_str("  ");
        schemas_index.push_str(exported.name);
        schemas_index.push_str(": ");
        schemas_index.push_str(schema_group_const(module));
        schemas_index.push('.');
        schemas_index.push_str(exported.name);
        schemas_index.push_str(",\n");
    }
    schemas_index.push_str("} as const;\n\n");
    schemas_index.push_str("export const gatewaySchemaRefs = [\n");
    for module in schema_groups.keys() {
        if schema_ref_groups
            .get(module)
            .is_some_and(|refs| !refs.is_empty())
        {
            schemas_index.push_str("  ...");
            schemas_index.push_str(schema_group_refs_const(module));
            schemas_index.push_str(",\n");
        }
    }
    schemas_index.push_str("] as const;\n\n");
    schemas_index.push_str("export type GatewaySchemaName = keyof typeof gatewaySchemas;\n");
    write_checked(
        &generated_schema_dir.join("index.ts"),
        &schemas_index,
        check,
    )?;

    let index = "// @generated by psychevo-xtask gateway-protocol generate\nexport * from './types';\nexport * from './schemas';\n";
    write_checked(&generated_dir.join("index.ts"), index, check)?;
    Ok(())
}

include!("codegen/schema_render.rs");
include!("codegen/schema_groups.rs");
include!("codegen/typescript.rs");
include!("codegen/exported_types.rs");
