#[derive(Debug, Clone, Copy)]
struct ExportedType {
    name: &'static str,
    ts_decl: fn() -> Result<String>,
    schema: fn() -> Result<Value>,
}

#[derive(Debug, Clone)]
struct SchemaGroupEntry {
    name: &'static str,
    json: String,
}

#[derive(Debug, Clone)]
struct SchemaRefEntry {
    export_name: String,
    import_path: String,
    json: String,
    schema_path: String,
}

pub fn generate_typescript_and_schema(repo_root: &Path, check: bool) -> Result<()> {
    let package_root = repo_root.join("packages/protocol");
    let generated_dir = package_root.join("src/generated");
    let generated_schema_dir = generated_dir.join("schemas");
    let schema_dir = package_root.join("schema");
    let mut ts = String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
    for exported in exported_types() {
        ts.push_str(&(exported.ts_decl)()?);
        ts.push_str("\n\n");
    }
    write_checked(&generated_dir.join("types.ts"), &ts, check)?;

    let legacy_schema_file = generated_dir.join("schemas.ts");
    if check {
        if legacy_schema_file.exists() {
            bail!(
                "obsolete generated file is present: {}",
                legacy_schema_file.display()
            );
        }
    } else {
        let _ = fs::remove_file(&legacy_schema_file);
        if generated_schema_dir.exists() {
            fs::remove_dir_all(&generated_schema_dir)?;
        }
        for composite in ["ClientRequest", "ServerNotification"] {
            let _ = fs::remove_dir_all(schema_dir.join(composite));
        }
    }

    let mut schema_groups: BTreeMap<&'static str, Vec<SchemaGroupEntry>> = BTreeMap::new();
    let mut schema_ref_groups: BTreeMap<&'static str, Vec<SchemaRefEntry>> = BTreeMap::new();
    for exported in exported_types() {
        let schema = (exported.schema)()?;
        let rendered = render_schema_export(exported.name, &schema)?;
        write_checked(
            &schema_dir.join(format!("{}.json", exported.name)),
            &(rendered.root_json.clone() + "\n"),
            check,
        )?;
        for ref_entry in &rendered.refs {
            write_checked(
                &schema_dir.join(&ref_entry.schema_path),
                &(ref_entry.json.clone() + "\n"),
                check,
            )?;
        }
        let module = schema_group_module(exported.name);
        schema_groups
            .entry(module)
            .or_default()
            .push(SchemaGroupEntry {
                name: exported.name,
                json: rendered.root_json,
            });
        schema_ref_groups
            .entry(module)
            .or_default()
            .extend(rendered.refs);
    }

    for (module, schemas) in &schema_groups {
        let mut group_ts =
            String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
        if let Some(refs) = schema_ref_groups.get(module) {
            for ref_entry in refs {
                group_ts.push_str("import { ");
                group_ts.push_str(&ref_entry.export_name);
                group_ts.push_str(" } from './");
                group_ts.push_str(&ref_entry.import_path);
                group_ts.push_str("';\n");
            }
            if !refs.is_empty() {
                group_ts.push('\n');
            }
        }
        group_ts.push_str("export const ");
        group_ts.push_str(schema_group_const(module));
        group_ts.push_str(" = {\n");
        for SchemaGroupEntry { name, json } in schemas {
            group_ts.push_str("  ");
            group_ts.push_str(name);
            group_ts.push_str(": ");
            group_ts.push_str(json);
            group_ts.push_str(",\n");
        }
        group_ts.push_str("} as const;\n");
        if let Some(refs) = schema_ref_groups.get(module)
            && !refs.is_empty()
        {
            group_ts.push_str("\nexport const ");
            group_ts.push_str(schema_group_refs_const(module));
            group_ts.push_str(" = [\n");
            for ref_entry in refs {
                group_ts.push_str("  ");
                group_ts.push_str(&ref_entry.export_name);
                group_ts.push_str(",\n");
            }
            group_ts.push_str("] as const;\n");
            for ref_entry in refs {
                let mut part_ts =
                    String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
                part_ts.push_str("export const ");
                part_ts.push_str(&ref_entry.export_name);
                part_ts.push_str(" = ");
                part_ts.push_str(&ref_entry.json);
                part_ts.push_str(" as const;\n");
                write_checked(
                    &generated_schema_dir.join(format!("{}.ts", ref_entry.import_path)),
                    &part_ts,
                    check,
                )?;
            }
        }
        write_checked(
            &generated_schema_dir.join(format!("{module}.ts")),
            &group_ts,
            check,
        )?;
    }

    let mut schemas_index =
        String::from("// @generated by psychevo-xtask gateway-protocol generate\n\n");
    for module in schema_groups.keys() {
        schemas_index.push_str("import { ");
        schemas_index.push_str(schema_group_const(module));
        if schema_ref_groups
            .get(module)
            .is_some_and(|refs| !refs.is_empty())
        {
            schemas_index.push_str(", ");
            schemas_index.push_str(schema_group_refs_const(module));
        }
        schemas_index.push_str(" } from './");
        schemas_index.push_str(module);
        schemas_index.push_str("';\n");
    }
    schemas_index.push_str("\nexport const gatewaySchemas = {\n");
    for exported in exported_types() {
        let module = schema_group_module(exported.name);
        schemas_index.push_str("  ");
        schemas_index.push_str(exported.name);
        schemas_index.push_str(": ");
        schemas_index.push_str(schema_group_const(module));
        schemas_index.push('.');
        schemas_index.push_str(exported.name);
        schemas_index.push_str(",\n");
    }
    schemas_index.push_str("} as const;\n\n");
    schemas_index.push_str("export const gatewaySchemaRefs = [\n");
    for module in schema_groups.keys() {
        if schema_ref_groups
            .get(module)
            .is_some_and(|refs| !refs.is_empty())
        {
            schemas_index.push_str("  ...");
            schemas_index.push_str(schema_group_refs_const(module));
            schemas_index.push_str(",\n");
        }
    }
    schemas_index.push_str("] as const;\n\n");
    schemas_index.push_str("export type GatewaySchemaName = keyof typeof gatewaySchemas;\n");
    write_checked(
        &generated_schema_dir.join("index.ts"),
        &schemas_index,
        check,
    )?;

    let index = "// @generated by psychevo-xtask gateway-protocol generate\nexport * from './types';\nexport * from './schemas';\n";
    write_checked(&generated_dir.join("index.ts"), index, check)?;
    Ok(())
}

fn render_schema_export(name: &'static str, schema: &Value) -> Result<SchemaRender> {
    if !matches!(name, "ClientRequest" | "ServerNotification") {
        return Ok(SchemaRender {
            root_json: serde_json::to_string_pretty(schema)?,
            refs: Vec::new(),
        });
    }
    let variants = schema
        .get("oneOf")
        .and_then(Value::as_array)
        .context("composite schema has no oneOf variants")?;
    let definitions = schema
        .get("definitions")
        .and_then(Value::as_object)
        .context("composite schema has no definitions")?;
    let mut refs = Vec::new();
    let mut root = schema.clone();
    let mut root_refs = Vec::new();
    for variant in variants {
        let method = composite_method(variant)?;
        let slug = schema_part_slug(method);
        let ref_id = format!("{name}/{slug}.json");
        root_refs.push(serde_json::json!({ "$ref": ref_id }));
        refs.push(SchemaRefEntry {
            export_name: schema_part_export_name(name, &slug),
            import_path: format!(
                "rpc/{}/{}",
                schema_part_slug(&kebab_case(name)),
                slug
            ),
            json: serde_json::to_string_pretty(&composite_part_schema(
                name,
                method,
                &ref_id,
                variant,
                definitions,
            )?)?,
            schema_path: format!("{name}/{slug}.json"),
        });
    }
    let root_object = root
        .as_object_mut()
        .context("composite root schema is not an object")?;
    root_object.remove("definitions");
    root_object.insert("oneOf".to_string(), Value::Array(root_refs));
    Ok(SchemaRender {
        root_json: serde_json::to_string_pretty(&root)?,
        refs,
    })
}

#[derive(Debug, Clone)]
struct SchemaRender {
    root_json: String,
    refs: Vec<SchemaRefEntry>,
}

fn composite_part_schema(
    root_name: &str,
    method: &str,
    ref_id: &str,
    variant: &Value,
    definitions: &serde_json::Map<String, Value>,
) -> Result<Value> {
    let mut object = serde_json::Map::new();
    object.insert(
        "$schema".to_string(),
        Value::String("http://json-schema.org/draft-07/schema#".to_string()),
    );
    object.insert("$id".to_string(), Value::String(ref_id.to_string()));
    object.insert(
        "title".to_string(),
        Value::String(format!("{root_name} {}", method)),
    );
    if let Some(variant_object) = variant.as_object() {
        for (key, value) in variant_object {
            object.insert(key.clone(), value.clone());
        }
    } else {
        bail!("composite variant for {root_name} is not an object");
    }
    let required_definitions = required_definitions(variant, definitions);
    if !required_definitions.is_empty() {
        object.insert("definitions".to_string(), Value::Object(required_definitions));
    }
    Ok(Value::Object(object))
}

fn required_definitions(
    value: &Value,
    definitions: &serde_json::Map<String, Value>,
) -> serde_json::Map<String, Value> {
    let mut pending = BTreeSet::new();
    collect_definition_refs(value, &mut pending);
    let mut seen = BTreeSet::new();
    let mut output = serde_json::Map::new();
    while let Some(name) = pending.iter().next().cloned() {
        pending.remove(&name);
        if !seen.insert(name.clone()) {
            continue;
        }
        let Some(definition) = definitions.get(&name) else {
            continue;
        };
        collect_definition_refs(definition, &mut pending);
        output.insert(name, definition.clone());
    }
    output
}

fn collect_definition_refs(value: &Value, refs: &mut BTreeSet<String>) {
    match value {
        Value::Object(object) => {
            if let Some(name) = object
                .get("$ref")
                .and_then(Value::as_str)
                .and_then(|value| value.strip_prefix("#/definitions/"))
            {
                refs.insert(name.to_string());
            }
            for nested in object.values() {
                collect_definition_refs(nested, refs);
            }
        }
        Value::Array(items) => {
            for item in items {
                collect_definition_refs(item, refs);
            }
        }
        _ => {}
    }
}

fn composite_method(variant: &Value) -> Result<&str> {
    variant
        .get("properties")
        .and_then(|value| value.get("method"))
        .and_then(|value| value.get("enum"))
        .and_then(Value::as_array)
        .and_then(|values| values.first())
        .and_then(Value::as_str)
        .context("composite schema variant has no method enum")
}

fn schema_part_slug(value: &str) -> String {
    kebab_case(value)
        .replace(['/', '_'], "-")
        .trim_matches('-')
        .to_string()
}

fn schema_part_export_name(root_name: &str, slug: &str) -> String {
    format!("{}{}Schema", lower_camel(root_name), pascal_case(slug))
}

fn kebab_case(value: &str) -> String {
    let mut output = String::new();
    for (index, ch) in value.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                output.push('-');
            }
            output.push(ch.to_ascii_lowercase());
        } else if ch.is_ascii_alphanumeric() || matches!(ch, '/' | '_' | '-') {
            output.push(ch.to_ascii_lowercase());
        } else {
            output.push('-');
        }
    }
    output
}

fn lower_camel(value: &str) -> String {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return String::new();
    };
    format!("{}{}", first.to_ascii_lowercase(), chars.collect::<String>())
}

fn pascal_case(value: &str) -> String {
    value
        .split(['-', '/', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let Some(first) = chars.next() else {
                return String::new();
            };
            format!("{}{}", first.to_ascii_uppercase(), chars.collect::<String>())
        })
        .collect::<Vec<_>>()
        .join("")
}

fn schema_group_module(name: &str) -> &'static str {
    if name.starts_with("JsonRpc") || matches!(name, "ClientRequest" | "ServerNotification") {
        return "rpc";
    }
    if name.starts_with("Source") || name.starts_with("GatewaySource") {
        return "source";
    }
    if name == "GatewayEvent" || name == "GatewaySelectedSkill" {
        return "gateway/events";
    }
    if matches!(
        name,
        "AgentListParams" | "AgentReadParams" | "AgentWriteParams" | "AgentDeleteParams"
    ) {
        return "gateway/agents/requests";
    }
    if matches!(
        name,
        "AgentListResult" | "AgentReadResult" | "AgentWriteResult" | "AgentDeleteResult"
    ) {
        return "gateway/agents/results";
    }
    if matches!(name, "AgentStatusParams" | "AgentStatusResult")
        || name.starts_with("AgentRun")
        || name == "AgentStatusControlView"
    {
        return "gateway/agents/runs";
    }
    if name.starts_with("Agent") {
        return "gateway/agents/definitions";
    }
    if name.starts_with("BackendDoctor") {
        return "gateway/backend/doctor";
    }
    if name.starts_with("Backend") {
        return "gateway/backend/config";
    }
    if matches!(name, "BackendKind" | "GatewayBackendInfo") {
        return "gateway/backend/core";
    }
    if matches!(
        name,
        "GatewayRequestScope"
            | "GatewayThreadSelector"
            | "GatewayThread"
            | "GatewayTurn"
            | "GatewayTurnStatus"
            | "GatewayInputPart"
            | "GatewayImageInput"
            | "GatewaySelectedSkill"
            | "GatewayEvent"
    ) || name.starts_with("GatewayMention")
    {
        return "gateway/core";
    }
    if name.starts_with("Transcript") {
        return "transcript";
    }
    if matches!(
        name,
        "ThreadSnapshot"
            | "ThreadListResult"
            | "ThreadBrowserResult"
            | "ThreadBrowserWorkspace"
            | "ThreadMutationResult"
            | "ThreadDeleteResult"
    ) {
        return "thread/results";
    }
    if name.starts_with("ThreadTrace") {
        return "thread/trace";
    }
    if name.starts_with("Thread") {
        return "thread/controls";
    }
    if name.starts_with("Session") || name == "GatewayActivityView" {
        return "thread/session";
    }
    if name.starts_with("Completion") {
        return "completion";
    }
    if name.starts_with("Command") {
        return "command";
    }
    if name.starts_with("Shell") {
        return "shell";
    }
    if name.starts_with("Runtime") {
        return "turn/runtime";
    }
    if matches!(
        name,
        "TurnStartParams"
            | "TurnSteerParams"
            | "TurnInterruptParams"
            | "TurnTakeoverParams"
            | "TurnStartResult"
            | "TurnControlResult"
            | "TurnTakeoverResult"
    ) {
        return "turn/control";
    }
    if name.starts_with("Turn") {
        return "turn/result";
    }
    if name.starts_with("Permission")
        || name.starts_with("Clarify")
        || name.starts_with("Pending")
        || name == "InteractionRespondResult"
    {
        return "interaction";
    }
    if name.starts_with("Settings") || name.starts_with("Workbench") {
        return "settings";
    }
    if name.starts_with("WorkspaceFile")
        || matches!(
            name,
            "WorkspaceFilesParams"
                | "WorkspaceFilesResult"
                | "WorkspaceCreateParams"
                | "WorkspaceCreateResult"
        )
    {
        return "workspace/files";
    }
    if name.starts_with("WorkspaceDiff")
        || name.starts_with("WorkspaceChange")
        || matches!(name, "WorkspaceChangesParams" | "WorkspaceChangesResult")
    {
        return "workspace/review";
    }
    if name.starts_with("Context") {
        return "context";
    }
    if name.starts_with("CreateLaunch") || name == "ManagedServerState" {
        return "launch";
    }
    "system"
}

fn schema_group_const(module: &str) -> &'static str {
    match module {
        "command" => "commandSchemas",
        "completion" => "completionSchemas",
        "context" => "contextSchemas",
        "gateway/agents/definitions" => "gatewayAgentDefinitionSchemas",
        "gateway/agents/requests" => "gatewayAgentRequestSchemas",
        "gateway/agents/results" => "gatewayAgentResultSchemas",
        "gateway/agents/runs" => "gatewayAgentRunSchemas",
        "gateway/backend/config" => "gatewayBackendConfigSchemas",
        "gateway/backend/core" => "gatewayBackendCoreSchemas",
        "gateway/backend/doctor" => "gatewayBackendDoctorSchemas",
        "gateway/core" => "gatewayCoreSchemas",
        "gateway/events" => "gatewayEventSchemas",
        "interaction" => "interactionSchemas",
        "launch" => "launchSchemas",
        "rpc" => "rpcSchemas",
        "settings" => "settingsSchemas",
        "shell" => "shellSchemas",
        "source" => "sourceSchemas",
        "system" => "systemSchemas",
        "thread/controls" => "threadControlSchemas",
        "thread/results" => "threadResultSchemas",
        "thread/session" => "threadSessionSchemas",
        "thread/trace" => "threadTraceSchemas",
        "transcript" => "transcriptSchemas",
        "turn/control" => "turnControlSchemas",
        "turn/result" => "turnResultSchemas",
        "turn/runtime" => "turnRuntimeSchemas",
        "workspace/files" => "workspaceFileSchemas",
        "workspace/review" => "workspaceReviewSchemas",
        _ => unreachable!("unknown schema group module"),
    }
}

fn schema_group_refs_const(module: &str) -> &'static str {
    match module {
        "command" => "commandSchemaRefs",
        "completion" => "completionSchemaRefs",
        "context" => "contextSchemaRefs",
        "gateway/agents/definitions" => "gatewayAgentDefinitionSchemaRefs",
        "gateway/agents/requests" => "gatewayAgentRequestSchemaRefs",
        "gateway/agents/results" => "gatewayAgentResultSchemaRefs",
        "gateway/agents/runs" => "gatewayAgentRunSchemaRefs",
        "gateway/backend/config" => "gatewayBackendConfigSchemaRefs",
        "gateway/backend/core" => "gatewayBackendCoreSchemaRefs",
        "gateway/backend/doctor" => "gatewayBackendDoctorSchemaRefs",
        "gateway/core" => "gatewayCoreSchemaRefs",
        "gateway/events" => "gatewayEventSchemaRefs",
        "interaction" => "interactionSchemaRefs",
        "launch" => "launchSchemaRefs",
        "rpc" => "rpcSchemaRefs",
        "settings" => "settingsSchemaRefs",
        "shell" => "shellSchemaRefs",
        "source" => "sourceSchemaRefs",
        "system" => "systemSchemaRefs",
        "thread/controls" => "threadControlSchemaRefs",
        "thread/results" => "threadResultSchemaRefs",
        "thread/session" => "threadSessionSchemaRefs",
        "thread/trace" => "threadTraceSchemaRefs",
        "transcript" => "transcriptSchemaRefs",
        "turn/control" => "turnControlSchemaRefs",
        "turn/result" => "turnResultSchemaRefs",
        "turn/runtime" => "turnRuntimeSchemaRefs",
        "workspace/files" => "workspaceFileSchemaRefs",
        "workspace/review" => "workspaceReviewSchemaRefs",
        _ => unreachable!("unknown schema group module"),
    }
}

fn write_checked(path: &Path, content: &str, check: bool) -> Result<()> {
    if check {
        let existing = fs::read_to_string(path).with_context(|| {
            format!(
                "generated file is missing or unreadable: {}",
                path.display()
            )
        })?;
        if existing != content {
            bail!("generated file is out of date: {}", path.display());
        }
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

fn ts_decl<T>() -> Result<String>
where
    T: TS,
{
    let decl = T::decl();
    Ok(export_ts_decl(camelize_ts_decl_numbers(decl)))
}

fn export_ts_decl(decl: String) -> String {
    if decl.starts_with("type ") || decl.starts_with("interface ") {
        format!("export {decl}")
    } else {
        decl
    }
}

fn camelize_ts_decl_numbers(mut decl: String) -> String {
    for (from, to) in [
        ("thread_id", "threadId"),
        ("source_key", "sourceKey"),
        ("visible_to_model", "visibleToModel"),
        ("turn_id", "turnId"),
        ("item_id", "itemId"),
        ("queue_position", "queuePosition"),
        ("request_id", "requestId"),
        ("tool_name", "toolName"),
        ("source_path", "sourcePath"),
        ("call_id", "callId"),
        ("native_id", "nativeId"),
        ("raw_id", "rawId"),
        ("raw_identity", "rawIdentity"),
        ("visible_name", "visibleName"),
        ("artifact_ids", "artifactIds"),
        ("created_at_ms", "createdAtMs"),
        ("updated_at_ms", "updatedAtMs"),
        ("event_type", "eventType"),
        ("active_turn_id", "activeTurnId"),
        ("queued_turns", "queuedTurns"),
        ("started_at_ms", "startedAtMs"),
        ("ended_at_ms", "endedAtMs"),
        ("archived_at_ms", "archivedAtMs"),
        ("message_count", "messageCount"),
        ("tool_call_count", "toolCallCount"),
        ("reasoning_effort", "reasoningEffort"),
        ("insert_text", "insertText"),
        ("sort_text", "sortText"),
        ("visible_text", "visibleText"),
        ("backend_ref", "backendRef"),
        ("relative_path", "relativePath"),
        ("target_kind", "targetKind"),
        ("permission_mode", "permissionMode"),
        ("permission_mode_options", "permissionModeOptions"),
        ("display_path", "displayPath"),
        ("model_options", "modelOptions"),
        ("mode_options", "modeOptions"),
        ("variant_options", "variantOptions"),
        ("used_tokens", "usedTokens"),
        ("context_limit", "contextLimit"),
        ("is_git_repo", "isGitRepo"),
        ("unified_diff", "unifiedDiff"),
        ("selected_path", "selectedPath"),
        ("max_bytes", "maxBytes"),
        ("max_lines", "maxLines"),
        ("omitted_bytes", "omittedBytes"),
        ("omitted_lines", "omittedLines"),
    ] {
        decl = decl.replace(from, to);
    }
    decl.replace("bigint", "number")
}

fn schema<T>() -> Result<Value>
where
    T: JsonSchema,
{
    serde_json::to_value(schemars::schema_for!(T)).map_err(Into::into)
}

macro_rules! exported_type {
    ($ty:ty) => {
        ExportedType {
            name: stringify!($ty),
            ts_decl: ts_decl::<$ty>,
            schema: schema::<$ty>,
        }
    };
}

fn exported_types() -> Vec<ExportedType> {
    vec![
        exported_type!(SourceKey),
        exported_type!(GatewaySourceLifetime),
        exported_type!(GatewaySource),
        exported_type!(GatewaySourceInput),
        exported_type!(GatewayRequestScope),
        exported_type!(GatewayThreadSelector),
        exported_type!(BackendKind),
        exported_type!(GatewayBackendInfo),
        exported_type!(GatewayThread),
        exported_type!(GatewayTurn),
        exported_type!(GatewayTurnStatus),
        exported_type!(GatewayInputPart),
        exported_type!(GatewayMentionRange),
        exported_type!(GatewayMentionTarget),
        exported_type!(GatewayMention),
        exported_type!(GatewayImageInput),
        exported_type!(GatewaySelectedSkill),
        exported_type!(GatewayEvent),
        exported_type!(PermissionDecision),
        exported_type!(TranscriptEntryRole),
        exported_type!(TranscriptBlockKind),
        exported_type!(TranscriptBlockStatus),
        exported_type!(TranscriptToolResult),
        exported_type!(TranscriptBlock),
        exported_type!(TranscriptEntry),
        exported_type!(GatewayActivityView),
        exported_type!(PendingPermissionView),
        exported_type!(PendingClarifyView),
        exported_type!(ThreadSnapshot),
        exported_type!(SessionProjectView),
        exported_type!(SessionSummaryView),
        exported_type!(InitializeParams),
        exported_type!(InitializeResult),
        exported_type!(GatewayProfileView),
        exported_type!(ThreadStartParams),
        exported_type!(ThreadResumeParams),
        exported_type!(ThreadReadParams),
        exported_type!(ThreadTraceParams),
        exported_type!(ThreadTraceResult),
        exported_type!(ThreadListParams),
        exported_type!(ThreadBrowserParams),
        exported_type!(ThreadBrowserCursor),
        exported_type!(ThreadBrowserResult),
        exported_type!(ThreadBrowserWorkspace),
        exported_type!(ThreadIdParams),
        exported_type!(ThreadRenameParams),
        exported_type!(ThreadListResult),
        exported_type!(ThreadMutationResult),
        exported_type!(ThreadDeleteResult),
        exported_type!(CompletionListParams),
        exported_type!(CompletionReplacement),
        exported_type!(CompletionItem),
        exported_type!(CompletionListResult),
        exported_type!(CommandListParams),
        exported_type!(CommandAlternateAction),
        exported_type!(CommandListItem),
        exported_type!(CommandListResult),
        exported_type!(CommandExecuteParams),
        exported_type!(CommandExecuteResult),
        exported_type!(AgentListParams),
        exported_type!(AgentReadParams),
        exported_type!(AgentBackendRefInput),
        exported_type!(AgentWriteParams),
        exported_type!(AgentDeleteParams),
        exported_type!(AgentStatusParams),
        exported_type!(AgentBackendRefView),
        exported_type!(AgentDiagnosticView),
        exported_type!(AgentDefinitionView),
        exported_type!(AgentRunView),
        exported_type!(AgentStatusControlView),
        exported_type!(AgentListResult),
        exported_type!(AgentReadResult),
        exported_type!(AgentWriteResult),
        exported_type!(AgentDeleteResult),
        exported_type!(AgentStatusResult),
        exported_type!(BackendConfigTarget),
        exported_type!(BackendListParams),
        exported_type!(BackendDoctorParams),
        exported_type!(BackendWriteParams),
        exported_type!(BackendDeleteParams),
        exported_type!(BackendConfigView),
        exported_type!(BackendListResult),
        exported_type!(BackendDiagnosticView),
        exported_type!(BackendDoctorCheck),
        exported_type!(BackendDoctorResult),
        exported_type!(BackendWriteResult),
        exported_type!(BackendDeleteResult),
        exported_type!(ShellStartParams),
        exported_type!(ShellStartResult),
        exported_type!(TerminalStartParams),
        exported_type!(TerminalStartResult),
        exported_type!(TerminalWriteParams),
        exported_type!(TerminalResizeParams),
        exported_type!(TerminalTerminateParams),
        exported_type!(TerminalMutationResult),
        exported_type!(TerminalOutputPayload),
        exported_type!(TerminalExitedPayload),
        exported_type!(TurnStartParams),
        exported_type!(TurnSteerParams),
        exported_type!(TurnInterruptParams),
        exported_type!(TurnTakeoverParams),
        exported_type!(RuntimeOptionsParams),
        exported_type!(RuntimeConfigOptionValueView),
        exported_type!(RuntimeConfigOptionView),
        exported_type!(RuntimeOptionsResult),
        exported_type!(TurnStartResult),
        exported_type!(TurnControlResult),
        exported_type!(TurnTakeoverResult),
        exported_type!(TurnResultPayload),
        exported_type!(TurnRunResult),
        exported_type!(TurnErrorPayload),
        exported_type!(ShellResultPayload),
        exported_type!(ShellErrorPayload),
        exported_type!(PermissionRespondParams),
        exported_type!(ClarifyRespondParams),
        exported_type!(InteractionRespondResult),
        exported_type!(SourceResetParams),
        exported_type!(SettingsReadParams),
        exported_type!(SettingsUpdateParams),
        exported_type!(SettingsReadResult),
        exported_type!(WorkbenchProjectView),
        exported_type!(WorkbenchControlsView),
        exported_type!(WorkspaceCreateParams),
        exported_type!(WorkspaceCreateResult),
        exported_type!(WorkspaceFileKind),
        exported_type!(WorkspaceFileEntry),
        exported_type!(WorkspaceFilesParams),
        exported_type!(WorkspaceFilesResult),
        exported_type!(WorkspaceFileReadParams),
        exported_type!(WorkspaceFileReadResult),
        exported_type!(WorkspaceFileWriteParams),
        exported_type!(WorkspaceFileWriteResult),
        exported_type!(WorkspaceDiffFileStatusView),
        exported_type!(WorkspaceDiffFileView),
        exported_type!(WorkspaceDiffTruncationView),
        exported_type!(WorkspaceDiffParams),
        exported_type!(WorkspaceDiffResult),
        exported_type!(WorkspaceChangeReviewStatusView),
        exported_type!(WorkspaceChangeFileView),
        exported_type!(WorkspaceChangeGroupView),
        exported_type!(WorkspaceChangesParams),
        exported_type!(WorkspaceChangesResult),
        exported_type!(WorkspaceChangeFileParams),
        exported_type!(WorkspaceChangeMutationResult),
        exported_type!(ContextReadParams),
        exported_type!(ContextUsageCategoryView),
        exported_type!(ContextReadResult),
        exported_type!(ObservabilityReadParams),
        exported_type!(SessionUsageSummaryView),
        exported_type!(ObservabilityReadResult),
        exported_type!(ReadyzResult),
        exported_type!(CreateLaunchParams),
        exported_type!(CreateLaunchResult),
        exported_type!(ManagedServerState),
        exported_type!(JsonRpcId),
        exported_type!(JsonRpcRequest),
        exported_type!(JsonRpcNotification),
        exported_type!(JsonRpcSuccess),
        exported_type!(JsonRpcErrorResponse),
        exported_type!(JsonRpcError),
        exported_type!(ClientRequest),
        exported_type!(ServerNotification),
    ]
}
