use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct RequestContract {
    pub(crate) method: &'static str,
    pub(crate) params_ts: String,
    pub(crate) result_ts: String,
}

macro_rules! request_registry {
    (
        $(
            $variant:ident => $method:literal {
                params: $params_module:ident::$params:ident,
                result: $result_module:ident::$result:ident
            }
        ),* $(,)?
    ) => {
        #[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, TS)]
        #[serde(tag = "method", content = "params")]
        pub enum ClientRequest {
            $(
                #[serde(rename = $method)]
                $variant(crate::$params_module::$params),
            )*
        }

        pub(crate) fn request_contracts() -> Vec<RequestContract> {
            vec![
                $(
                    RequestContract {
                        method: $method,
                        params_ts: <crate::$params_module::$params as TS>::name(),
                        result_ts: <crate::$result_module::$result as TS>::name(),
                    },
                )*
            ]
        }
    };
}

request_registry! {
    Initialize => "initialize" { params: thread_command_turn::InitializeParams, result: thread_command_turn::InitializeResult },
    ThreadDraftOpen => "thread/draft/open" { params: thread_command_turn::ThreadDraftOpenParams, result: agents_backend_rpc::ThreadDraftOpenResult },
    ThreadResume => "thread/resume" { params: thread_command_turn::ThreadResumeParams, result: events_transcript::ThreadSnapshot },
    ThreadRead => "thread/read" { params: thread_command_turn::ThreadReadParams, result: events_transcript::ThreadSnapshot },
    ThreadTrace => "thread/trace" { params: thread_command_turn::ThreadTraceParams, result: thread_command_turn::ThreadTraceResult },
    ThreadList => "thread/list" { params: thread_command_turn::ThreadListParams, result: thread_command_turn::ThreadListResult },
    ThreadBrowser => "thread/browser" { params: thread_command_turn::ThreadBrowserParams, result: thread_command_turn::ThreadBrowserResult },
    ThreadRename => "thread/rename" { params: thread_command_turn::ThreadRenameParams, result: thread_command_turn::ThreadMutationResult },
    ThreadArchive => "thread/archive" { params: thread_command_turn::ThreadIdParams, result: thread_command_turn::ThreadMutationResult },
    ThreadRestore => "thread/restore" { params: thread_command_turn::ThreadIdParams, result: thread_command_turn::ThreadMutationResult },
    ThreadDelete => "thread/delete" { params: thread_command_turn::ThreadIdParams, result: thread_command_turn::ThreadDeleteResult },
    TurnStart => "turn/start" { params: thread_command_turn::TurnStartParams, result: thread_command_turn::TurnStartResult },
    ThreadContextRead => "thread/context/read" { params: agents_backend_rpc::ThreadContextReadParams, result: agents_backend_rpc::ThreadContextReadResult },
    ThreadDraftPrepare => "thread/draft/prepare" { params: agents_backend_rpc::ThreadDraftPrepareParams, result: agents_backend_rpc::ThreadDraftPrepareResult },
    ThreadControlSet => "thread/control/set" { params: agents_backend_rpc::ThreadControlSetParams, result: agents_backend_rpc::ThreadControlSetResult },
    ThreadActionRun => "thread/action/run" { params: thread_command_turn::ThreadActionRunParams, result: thread_command_turn::ThreadActionRunResult },
    ThreadInteractionRespond => "thread/interaction/respond" { params: thread_command_turn::ThreadInteractionRespondParams, result: thread_command_turn::ThreadInteractionRespondResult },
    ThreadHistoryRead => "thread/history/read" { params: thread_command_turn::ThreadHistoryReadParams, result: thread_command_turn::ThreadHistoryReadResult },
    ThreadHistoryDraftRead => "thread/history/draft/read" { params: thread_command_turn::ThreadHistoryDraftReadParams, result: thread_command_turn::ThreadHistoryDraftReadResult },
    ThreadImportList => "thread/import/list" { params: agents_backend_rpc::ThreadImportListParams, result: agents_backend_rpc::ThreadImportListResult },
    ThreadImport => "thread/import" { params: agents_backend_rpc::ThreadImportParams, result: agents_backend_rpc::ThreadImportResult },
    RuntimeProfileList => "runtime/profile/list" { params: agents_backend_rpc::RuntimeProfileListParams, result: agents_backend_rpc::RuntimeProfileListResult },
    RuntimeProfileRead => "runtime/profile/read" { params: agents_backend_rpc::RuntimeProfileReadParams, result: agents_backend_rpc::RuntimeProfileReadResult },
    RuntimeProfileWrite => "runtime/profile/write" { params: agents_backend_rpc::RuntimeProfileWriteParams, result: agents_backend_rpc::RuntimeProfileWriteResult },
    RuntimeProfileDelete => "runtime/profile/delete" { params: agents_backend_rpc::RuntimeProfileDeleteParams, result: agents_backend_rpc::RuntimeProfileDeleteResult },
    RuntimeProfileSetEnabled => "runtime/profile/setEnabled" { params: agents_backend_rpc::RuntimeProfileSetEnabledParams, result: agents_backend_rpc::RuntimeProfileWriteResult },
    AutomationList => "automation/list" { params: automations::AutomationListParams, result: automations::AutomationListResult },
    AutomationDraft => "automation/draft" { params: automations::AutomationDraftParams, result: automations::AutomationDraftResult },
    AutomationWrite => "automation/write" { params: automations::AutomationWriteParams, result: automations::AutomationMutationResult },
    AutomationPause => "automation/pause" { params: automations::AutomationIdParams, result: automations::AutomationMutationResult },
    AutomationResume => "automation/resume" { params: automations::AutomationIdParams, result: automations::AutomationMutationResult },
    AutomationDelete => "automation/delete" { params: automations::AutomationIdParams, result: automations::AutomationDeleteResult },
    AutomationRun => "automation/run" { params: automations::AutomationRunParams, result: automations::AutomationRunResult },
    CompletionList => "completion/list" { params: thread_command_turn::CompletionListParams, result: thread_command_turn::CompletionListResult },
    CommandList => "command/list" { params: thread_command_turn::CommandListParams, result: thread_command_turn::CommandListResult },
    CommandExecute => "command/execute" { params: thread_command_turn::CommandExecuteParams, result: thread_command_turn::CommandExecuteResult },
    SlashSettingsRead => "slash/settings/read" { params: thread_command_turn::SlashSettingsReadParams, result: thread_command_turn::SlashSettingsResult },
    SlashSettingsUpdate => "slash/settings/update" { params: thread_command_turn::SlashSettingsUpdateParams, result: thread_command_turn::SlashSettingsResult },
    AgentList => "agent/list" { params: agents_backend_rpc::AgentListParams, result: agents_backend_rpc::AgentListResult },
    AgentRead => "agent/read" { params: agents_backend_rpc::AgentReadParams, result: agents_backend_rpc::AgentReadResult },
    AgentWrite => "agent/write" { params: agents_backend_rpc::AgentWriteParams, result: agents_backend_rpc::AgentWriteResult },
    AgentSetEnabled => "agent/setEnabled" { params: agents_backend_rpc::AgentSetEnabledParams, result: agents_backend_rpc::AgentSetEnabledResult },
    AgentDelete => "agent/delete" { params: agents_backend_rpc::AgentDeleteParams, result: agents_backend_rpc::AgentDeleteResult },
    AgentStatus => "agent/status" { params: agents_backend_rpc::AgentStatusParams, result: agents_backend_rpc::AgentStatusResult },
    TeamList => "team/list" { params: agents_backend_rpc::TeamListParams, result: agents_backend_rpc::TeamListResult },
    TeamRead => "team/read" { params: agents_backend_rpc::TeamReadParams, result: agents_backend_rpc::TeamReadResult },
    TeamWrite => "team/write" { params: agents_backend_rpc::TeamWriteParams, result: agents_backend_rpc::TeamWriteResult },
    TeamSetEnabled => "team/setEnabled" { params: agents_backend_rpc::TeamSetEnabledParams, result: agents_backend_rpc::TeamSetEnabledResult },
    TeamDelete => "team/delete" { params: agents_backend_rpc::TeamDeleteParams, result: agents_backend_rpc::TeamDeleteResult },
    TeamStatus => "team/status" { params: agents_backend_rpc::TeamStatusParams, result: agents_backend_rpc::TeamStatusResult },
    AgentControl => "agent/control" { params: agents_backend_rpc::AgentControlParams, result: agents_backend_rpc::AgentControlResult },
    BackendList => "backend/list" { params: agents_backend_rpc::BackendListParams, result: agents_backend_rpc::BackendListResult },
    BackendDoctor => "backend/doctor" { params: agents_backend_rpc::BackendDoctorParams, result: agents_backend_rpc::BackendDoctorResult },
    BackendInstall => "backend/install" { params: agents_backend_rpc::BackendManageParams, result: agents_backend_rpc::BackendManageResult },
    BackendRepair => "backend/repair" { params: agents_backend_rpc::BackendManageParams, result: agents_backend_rpc::BackendManageResult },
    BackendUpgrade => "backend/upgrade" { params: agents_backend_rpc::BackendManageParams, result: agents_backend_rpc::BackendManageResult },
    BackendWrite => "backend/write" { params: agents_backend_rpc::BackendWriteParams, result: agents_backend_rpc::BackendWriteResult },
    BackendDelete => "backend/delete" { params: agents_backend_rpc::BackendDeleteParams, result: agents_backend_rpc::BackendDeleteResult },
    PluginList => "plugin/list" { params: agents_backend_rpc::PluginListParams, result: capability_results::PluginListResult },
    PluginRead => "plugin/read" { params: agents_backend_rpc::PluginReadParams, result: capability_results::PluginReadResult },
    PluginDoctor => "plugin/doctor" { params: agents_backend_rpc::PluginDoctorParams, result: capability_results::PluginDoctorResult },
    PluginInspect => "plugin/import/inspect" { params: agents_backend_rpc::PluginInspectParams, result: capability_results::PluginInspectResult },
    PluginInstall => "plugin/install" { params: agents_backend_rpc::PluginInstallParams, result: capability_results::PluginInstallResult },
    PluginUninstall => "plugin/uninstall" { params: agents_backend_rpc::PluginUninstallParams, result: capability_results::PluginUninstallResult },
    PluginSetEnabled => "plugin/setEnabled" { params: agents_backend_rpc::PluginSetEnabledParams, result: capability_results::PluginSetEnabledResult },
    PluginAuthorityWrite => "plugin/authority/write" { params: agents_backend_rpc::PluginAuthorityWriteParams, result: capability_results::PluginAuthorityWriteResult },
    PluginAuthorityRefresh => "plugin/authority/refresh" { params: agents_backend_rpc::PluginAuthorityRefreshParams, result: capability_results::PluginAuthorityRefreshResult },
    PluginAuthoritySetTrust => "plugin/authority/setTrust" { params: agents_backend_rpc::PluginAuthoritySetTrustParams, result: capability_results::PluginAuthoritySetTrustResult },
    PluginCatalogList => "plugin/catalog/list" { params: agents_backend_rpc::PluginCatalogListParams, result: capability_results::PluginCatalogListResult },
    PluginCatalogAdd => "plugin/catalog/add" { params: agents_backend_rpc::PluginCatalogAddParams, result: capability_results::PluginCatalogAddResult },
    PluginCatalogRemove => "plugin/catalog/remove" { params: agents_backend_rpc::PluginCatalogRemoveParams, result: capability_results::PluginCatalogRemoveResult },
    PluginCatalogUpgrade => "plugin/catalog/upgrade" { params: agents_backend_rpc::PluginCatalogUpgradeParams, result: capability_results::PluginCatalogUpgradeResult },
    PluginConnectStart => "plugin/connect/start" { params: agents_backend_rpc::PluginConnectStartParams, result: capability_results::PluginConnectStartResult },
    PluginConnectStatus => "plugin/connect/status" { params: agents_backend_rpc::PluginConnectStatusParams, result: capability_results::PluginConnectStatusResult },
    ExtensionList => "extension/list" { params: agents_backend_rpc::ExtensionListParams, result: capability_results::ExtensionListResult },
    ExtensionRead => "extension/read" { params: agents_backend_rpc::ExtensionReadParams, result: capability_results::ExtensionReadResult },
    ExtensionRemove => "extension/remove" { params: agents_backend_rpc::ExtensionRemoveParams, result: capability_results::ExtensionMutationResult },
    ExtensionSetEnabled => "extension/setEnabled" { params: agents_backend_rpc::ExtensionSetEnabledParams, result: capability_results::ExtensionMutationResult },
    ExtensionAppOpen => "extension/app/open" { params: agents_backend_rpc::ExtensionAppOpenParams, result: capability_results::ExtensionAppOpenResult },
    ExtensionAppClose => "extension/app/close" { params: agents_backend_rpc::ExtensionAppCloseParams, result: capability_results::ExtensionAppCloseResult },
    SkillList => "skill/list" { params: agents_backend_rpc::SkillListParams, result: capability_results::SkillListResult },
    SkillRead => "skill/read" { params: agents_backend_rpc::SkillReadParams, result: capability_results::SkillReadResult },
    SkillInstall => "skill/install" { params: agents_backend_rpc::SkillInstallParams, result: capability_results::SkillInstallResult },
    SkillUninstall => "skill/uninstall" { params: agents_backend_rpc::SkillUninstallParams, result: capability_results::SkillUninstallResult },
    SkillSetEnabled => "skill/setEnabled" { params: agents_backend_rpc::SkillSetEnabledParams, result: capability_results::SkillSetEnabledResult },
    SkillWrite => "skill/write" { params: agents_backend_rpc::SkillWriteParams, result: agents_backend_rpc::SkillWriteResult },
    ToolList => "tool/list" { params: agents_backend_rpc::ToolListParams, result: capability_results::ToolListResult },
    ToolRead => "tool/read" { params: agents_backend_rpc::ToolReadParams, result: capability_results::ToolReadResult },
    ToolSetEnabled => "tool/setEnabled" { params: agents_backend_rpc::ToolSetEnabledParams, result: capability_results::ToolMutationResult },
    ToolCreate => "tool/create" { params: agents_backend_rpc::ToolCreateParams, result: capability_results::ToolMutationResult },
    ToolRemove => "tool/remove" { params: agents_backend_rpc::ToolRemoveParams, result: capability_results::ToolMutationResult },
    McpList => "mcp/list" { params: agents_backend_rpc::McpListParams, result: capability_results::McpListResult },
    McpRead => "mcp/read" { params: agents_backend_rpc::McpReadParams, result: capability_results::McpReadResult },
    McpUpsert => "mcp/upsert" { params: agents_backend_rpc::McpUpsertParams, result: capability_results::McpMutationResult },
    McpRemove => "mcp/remove" { params: agents_backend_rpc::McpNameParams, result: capability_results::McpMutationResult },
    McpSetEnabled => "mcp/setEnabled" { params: agents_backend_rpc::McpSetEnabledParams, result: capability_results::McpMutationResult },
    McpSetToolPolicy => "mcp/setToolPolicy" { params: agents_backend_rpc::McpSetToolPolicyParams, result: capability_results::McpMutationResult },
    McpTest => "mcp/test" { params: agents_backend_rpc::McpNameParams, result: capability_results::McpTestResult },
    McpOAuthStart => "mcp/oauth/start" { params: agents_backend_rpc::McpOAuthStartParams, result: capability_results::McpOAuthStartResult },
    McpOAuthStatus => "mcp/oauth/status" { params: agents_backend_rpc::McpOAuthStatusParams, result: capability_results::McpOAuthStatusResult },
    McpOAuthLogout => "mcp/oauth/logout" { params: agents_backend_rpc::McpNameParams, result: capability_results::McpOAuthLogoutResult },
    ChannelList => "channel/list" { params: channels::ChannelListParams, result: channels::ChannelListResult },
    ChannelShow => "channel/show" { params: channels::ChannelIdParams, result: channels::ChannelEnableResult },
    ChannelEnable => "channel/enable" { params: channels::ChannelEnableParams, result: channels::ChannelEnableResult },
    ChannelUpdate => "channel/update" { params: channels::ChannelUpdateParams, result: channels::ChannelEnableResult },
    ChannelDelete => "channel/delete" { params: channels::ChannelIdParams, result: channels::ChannelListResult },
    ChannelDoctor => "channel/doctor" { params: channels::ChannelDoctorParams, result: channels::ChannelDoctorResult },
    ChannelSourceList => "channel/source/list" { params: channels::ChannelIdParams, result: channels::ChannelSourceListResult },
    ChannelWechatQrStart => "channel/wechat-qr/start" { params: channels::ChannelWechatQrStartParams, result: channels::ChannelWechatQrStartResult },
    ChannelWechatQrPoll => "channel/wechat-qr/poll" { params: channels::ChannelWechatQrPollParams, result: channels::ChannelWechatQrPollResult },
    ShellStart => "shell/start" { params: thread_command_turn::ShellStartParams, result: thread_command_turn::ShellStartResult },
    TerminalStart => "terminal/start" { params: thread_command_turn::TerminalStartParams, result: thread_command_turn::TerminalStartResult },
    TerminalWrite => "terminal/write" { params: thread_command_turn::TerminalWriteParams, result: thread_command_turn::TerminalMutationResult },
    TerminalResize => "terminal/resize" { params: thread_command_turn::TerminalResizeParams, result: thread_command_turn::TerminalMutationResult },
    TerminalTerminate => "terminal/terminate" { params: thread_command_turn::TerminalTerminateParams, result: thread_command_turn::TerminalMutationResult },
    SourceReset => "source/reset" { params: thread_command_turn::SourceResetParams, result: events_transcript::ThreadSnapshot },
    SettingsUpdate => "settings/update" { params: settings_workspace_context::SettingsUpdateParams, result: settings_workspace_context::SettingsReadResult },
    SettingsRead => "settings/read" { params: settings_workspace_context::SettingsReadParams, result: settings_workspace_context::SettingsReadResult },
    WebSearchSettingsRead => "web/search/settings/read" { params: settings_workspace_context::WebSearchSettingsReadParams, result: settings_workspace_context::WebSearchSettingsView },
    WebSearchSettingsUpdate => "web/search/settings/update" { params: settings_workspace_context::WebSearchSettingsUpdateParams, result: settings_workspace_context::WebSearchSettingsView },
    ModelSettingsRead => "model/settings/read" { params: settings_workspace_context::ModelSettingsReadParams, result: settings_workspace_context::ModelSettingsResult },
    ModelProviderSave => "model/provider/save" { params: settings_workspace_context::ModelProviderSaveParams, result: settings_workspace_context::ModelSettingsResult },
    ModelProviderCatalog => "model/provider/catalog" { params: settings_workspace_context::ModelProviderCatalogParams, result: settings_workspace_context::ModelProviderCatalogResult },
    ModelStateRead => "model/state/read" { params: settings_workspace_context::ModelStateReadParams, result: settings_workspace_context::ModelStateResult },
    ModelStateSet => "model/state/set" { params: settings_workspace_context::ModelStateSetParams, result: settings_workspace_context::ModelStateResult },
    ModelAssignmentSet => "model/assignment/set" { params: settings_workspace_context::ModelAssignmentSetParams, result: settings_workspace_context::ModelAssignmentSetResult },
    VoiceAsrTranscribe => "voice/asr/transcribe" { params: voice::VoiceAsrTranscribeParams, result: voice::VoiceAsrTranscribeResult },
    VoiceTtsSynthesize => "voice/tts/synthesize" { params: voice::VoiceTtsSynthesizeParams, result: voice::VoiceTtsSynthesizeResult },
    VoicePolicyRead => "voice/policy/read" { params: voice::VoicePolicyReadParams, result: voice::VoicePolicyResult },
    VoicePolicyUpdate => "voice/policy/update" { params: voice::VoicePolicyUpdateParams, result: voice::VoicePolicyResult },
    ThreadRealtimeStart => "thread/realtime/start" { params: voice::ThreadRealtimeStartParams, result: voice::ThreadRealtimeStartResult },
    ThreadRealtimeAppendAudio => "thread/realtime/appendAudio" { params: voice::ThreadRealtimeAppendAudioParams, result: voice::ThreadRealtimeMutationResult },
    ThreadRealtimeAppendText => "thread/realtime/appendText" { params: voice::ThreadRealtimeAppendTextParams, result: voice::ThreadRealtimeMutationResult },
    ThreadRealtimeAppendSpeech => "thread/realtime/appendSpeech" { params: voice::ThreadRealtimeAppendSpeechParams, result: voice::ThreadRealtimeMutationResult },
    ThreadRealtimeStop => "thread/realtime/stop" { params: voice::ThreadRealtimeSessionParams, result: voice::ThreadRealtimeMutationResult },
    ThreadRealtimeListVoices => "thread/realtime/listVoices" { params: voice::ThreadRealtimeSessionParams, result: voice::ThreadRealtimeListVoicesResult },
    WorkspaceFiles => "workspace/files" { params: settings_workspace_context::WorkspaceFilesParams, result: settings_workspace_context::WorkspaceFilesResult },
    WorkspaceFolderList => "workspace/folders" { params: settings_workspace_context::WorkspaceFolderListParams, result: settings_workspace_context::WorkspaceFolderListResult },
    WorkspaceGitBranches => "workspace/git/branches" { params: settings_workspace_context::WorkspaceGitBranchesParams, result: settings_workspace_context::WorkspaceGitBranchesResult },
    WorkspaceGitCheckout => "workspace/git/checkout" { params: settings_workspace_context::WorkspaceGitCheckoutParams, result: settings_workspace_context::WorkspaceGitBranchesResult },
    WorkspaceFileRead => "workspace/file/read" { params: settings_workspace_context::WorkspaceFileReadParams, result: settings_workspace_context::WorkspaceFileReadResult },
    WorkspaceFilePreviewOpen => "workspace/file/preview/open" { params: settings_workspace_context::WorkspaceFilePreviewOpenParams, result: settings_workspace_context::WorkspaceFilePreviewOpenResult },
    WorkspaceFilePreviewRelease => "workspace/file/preview/release" { params: settings_workspace_context::WorkspaceFilePreviewReleaseParams, result: settings_workspace_context::WorkspaceFilePreviewReleaseResult },
    WorkspaceFileWrite => "workspace/file/write" { params: settings_workspace_context::WorkspaceFileWriteParams, result: settings_workspace_context::WorkspaceFileWriteResult },
    WorkspaceFileExternalActions => "workspace/file/externalActions" { params: settings_workspace_context::WorkspaceFileExternalActionsParams, result: settings_workspace_context::WorkspaceFileExternalActionsResult },
    WorkspaceFileOpenExternal => "workspace/file/openExternal" { params: settings_workspace_context::WorkspaceFileOpenExternalParams, result: settings_workspace_context::WorkspaceFileOpenExternalResult },
    WorkspaceDiff => "workspace/diff" { params: settings_workspace_context::WorkspaceDiffParams, result: settings_workspace_context::WorkspaceDiffResult },
    WorkspaceChanges => "workspace/changes" { params: settings_workspace_context::WorkspaceChangesParams, result: settings_workspace_context::WorkspaceChangesResult },
    WorkspaceChangeAccept => "workspace/change/accept" { params: settings_workspace_context::WorkspaceChangeFileParams, result: settings_workspace_context::WorkspaceChangeMutationResult },
    WorkspaceChangeReject => "workspace/change/reject" { params: settings_workspace_context::WorkspaceChangeFileParams, result: settings_workspace_context::WorkspaceChangeMutationResult },
    WorkspaceCreate => "workspace/create" { params: settings_workspace_context::WorkspaceCreateParams, result: settings_workspace_context::WorkspaceCreateResult },
    ContextRead => "context/read" { params: settings_workspace_context::ContextReadParams, result: settings_workspace_context::ContextReadResult },
    ObservabilityRead => "observability/read" { params: settings_workspace_context::ObservabilityReadParams, result: settings_workspace_context::ObservabilityReadResult },
    UsageRead => "usage/read" { params: settings_workspace_context::UsageReadParams, result: settings_workspace_context::UsageReadResult },
}
